<?php

/*---------------------------------------------------------------------------------------------------------
Program Title: Playlist Management Module

Programmers:    Marzan, Kristina Amor A.
                Millano, Ryan Kris F.
                Narisma, Anaise Nicole M.
                Seño, Lei Hant L.

Where the program fits in the general system designs:
This controller handles OAuth integration with Spotify and exporting user playlists to Spotify.
It acts as a thin layer between web routes and the SpotifyService which performs API interactions.

Date Written: July 2025
Date Revised: November 2025

Purpose: 
- Initiate Spotify OAuth authorization flow for the current user.
- Handle the OAuth callback and persist tokens via SpotifyService.
- Export a user's playlist and its tracks to the connected Spotify account.

Data structures, algorithms, and control:
- Playlist model with loaded songs and their spotify_uri fields.
- Arrays: lists of scopes, track URIs passed to Spotify API.
- OAuth redirect and callback handling (redirectToSpotify, handleCallback).
- Guard clauses to ensure authenticated user and ownership before exporting.
- Service delegation: SpotifyService encapsulates token management and API calls.
- Error handling for third-party API exceptions, returning user-friendly messages.

----------------------------------------------------------------------------------------------------------*/

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Playlist;
use App\Services\SpotifyService;

class SpotifyController extends Controller
{
    // Inject SpotifyService responsible for OAuth/token storage and API interactions.
    public function __construct(private SpotifyService $spotify)
    {
    }

    // Redirect the user to Spotify's authorization page with required scopes.
    public function redirectToSpotify()
    {
        $authorizeUrl = $this->spotify->getAuthorizeUrl([
            'playlist-modify-public',
            'playlist-modify-private',
        ]);
        return redirect($authorizeUrl);
    }

    // Handle Spotify's OAuth callback, persist tokens, and redirect back to playlists.
    public function handleCallback(Request $request)
    {
        $this->spotify->handleCallback($request->code);
        return redirect()->route('playlist.index')->with('success', 'Spotify account connected!');
    }

    // Export a user's playlist to their Spotify account.
    public function export(Request $request, Playlist $playlist)
    {
        // Ensure user is logged in before attempting export.
        if (!Auth::check()) {
            return redirect()->route('login');
        }

        // Ensure the current user owns the playlist before exporting.
        if ($playlist->user_id !== Auth::id()) {
            abort(403);
        }

        // Ensure songs relationship is loaded for track URIs.
        $playlist->loadMissing('songs');

        // Ensure we have a user API; if missing tokens redirect to auth route
        $api = $this->spotify->userApi();
        if (!$api) {
            return redirect()->route('spotify.auth');
        }

        try {
            // Use service to create a Spotify playlist and add track URIs that have spotify_uri.
            $created = $this->spotify->createPlaylistWithTracks(
                $playlist->name,
                'Generated by MoodMix',
                false,
                $playlist->songs->pluck('spotify_uri')->filter()->values()->all()
            );
        } catch (\SpotifyWebAPI\SpotifyWebAPIException $e) {
            // Bubble an error back to the user in a friendly manner.
            return back()->with('error', 'Spotify error: ' . $e->getMessage());
        }

        $spotifyUrl = 'https://open.spotify.com/playlist/' . $created->id;
        return redirect()
            ->route('playlist.show', $playlist)
            ->with('success', 'Your playlist has been exported! <a href="' . $spotifyUrl . '" target="_blank" 
            style="color: #c4b537; text-decoration: underline;">Tap here to check it out!</a>');
    }
}
