<?php

/*---------------------------------------------------------------------------------------------------------
Program Title: Playlist Management Module

Programmers:    Marzan, Kristina Amor A.
                Millano, Ryan Kris F.
                Narisma, Anaise Nicole M.
                Seño, Lei Hant L.

Where the program fits in the general system designs:

Date Written: July 2025
Date Revised: November 2025

Purpose: 

Data structures, algorithms, and control:

----------------------------------------------------------------------------------------------------------*/

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Playlist;
use App\Services\SpotifyService;

class SpotifyController extends Controller
{
    public function __construct(private SpotifyService $spotify)
    {
    }

    public function redirectToSpotify()
    {
        $authorizeUrl = $this->spotify->getAuthorizeUrl([
            'playlist-modify-public',
            'playlist-modify-private',
        ]);
        return redirect($authorizeUrl);
    }

    public function handleCallback(Request $request)
    {
        $this->spotify->handleCallback($request->code);
        return redirect()->route('playlist.index')->with('success', 'Spotify account connected!');
    }

    public function export(Request $request, Playlist $playlist)
    {
        if (!Auth::check()) {
            return redirect()->route('login');
        }

        if ($playlist->user_id !== Auth::id()) {
            abort(403);
        }

        // Ensure songs are loaded
        $playlist->loadMissing('songs');

        // Ensure we have a user API; if missing tokens redirect to auth route
        $api = $this->spotify->userApi();
        if (!$api) {
            return redirect()->route('spotify.auth');
        }

        try {
            $created = $this->spotify->createPlaylistWithTracks(
                $playlist->name,
                'Generated by MoodMix',
                false,
                $playlist->songs->pluck('spotify_uri')->filter()->values()->all()
            );
        } catch (\SpotifyWebAPI\SpotifyWebAPIException $e) {
            return back()->with('error', 'Spotify error: ' . $e->getMessage());
        }

        $spotifyUrl = 'https://open.spotify.com/playlist/' . $created->id;
        return redirect()
            ->route('playlist.show', $playlist)
            ->with('success', 'Your playlist has been exported! <a href="' . $spotifyUrl . '" target="_blank" style="color: #c4b537; text-decoration: underline;">Tap here to check it out!</a>');
    }
}
